name: Metrics

on:
  schedule: [{ cron: "0 0 * * 1" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Generate isometric calendar
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
        filename: metrics.plugin.isocalendar.svg
        output_action: commit
        committer_token: ${{ secrets.GITHUB_TOKEN }}

